[package]
name = "graph-assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = { version = "0.8.3", features = [
  "all",
  "dot_parser",
  "stable_graph",
] }
serde = { version = "1.0", features = ["derive"] }
